# some of the things configured under this file:
#     a. import paths
#     b. test discovery: python_files = test_*.py, python_functions = test_*
#     c. cmd line options addopts = -v --strict-markers
#     d. markers: markers = smoke: quick smoke tests
#     e. filter logs: filterwarnings = error

[pytest]
pythonpath = .